### ISSUE TITLE
Example request for static files webserver

### ISSUE THREAD

**Issue by vanvuongngo** [ThingPulse/epulse-feather-c6-samples#1]
Hi there,

your project is looking interesting. The ESP32-C6 would be a great option as a webserver because of the WiFi 6 Low Power consumption feature. But the espressif arduino library is still in an early state and I could not manage to use common webserver libraries. Do have an example for a webserver (including serving static files)?

best regards

**Comment by squix78** [comment]
Hi @vanvuongngo 
Support in platformio is currently very limited. But I just tried the SimpleWebServer example on the epulse-feather from the Arduino IDE and it works perfectly fine: https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/examples/SimpleWiFiServer/SimpleWiFiServer.ino

**Comment by vanvuongngo** [comment]
Thanks a lot and I have a look.
